spring:
  application:
    name: nexthw

#  config:
#    import:
#      - classpath:/properties/application-local.yml
  profiles:
    active: local

  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher