name: Network Connectivity Test

on:
  push:
    branches:
      - main

jobs:
  ping-test:
    runs-on: ubuntu-latest

    steps:
      - name: Test Ping to Server
        run: |
          echo "Pinging the server..."
          ping -c 4 ${{ secrets.SERVER_HOST }}