name: SSH Connection Test

on:
  push:
    branches:
      - main

jobs:
  CI:
    runs-on: ubuntu-20.04

    steps:
      - name: Run CI Tests
        run: echo "Running CI tests"

  CD:
    needs: CI  # CI 작업이 완료된 후에 실행
    runs-on: ubuntu-20.04

    steps:
      - uses: actions/checkout@v3

      - name: Run scripts in server
        uses: appleboy/ssh-action@master
        with:
          key: ${{ secrets.SERVER_KEY }}
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          port: 22
          script: |
            whoami