CD:
  needs: CI
  runs-on: ubuntu-20.04

  steps:
    - uses: actions/checkout@v3

    - name: Run scripts in server
      uses: appleboy/ssh-action@master
      with:
        key: ${{ secrets.SERVER_KEY }}
        host: ${{ secrets.SERVER_HOST }}
        username: ${{ secrets.SERVER_USER }}
        port: 22
        script: |
          whoami