name: Gradle Build & Podman-Compose Deploy

on:
  push:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # (1) 코드 체크아웃
      - name: Checkout Code
        uses: actions/checkout@v3

      # (2) JDK 11 세팅
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'

      # (3) application.yml 파일 생성
      - name: Create application.yml
        run: |
          mkdir -p ./src/main/resources
          touch ./src/main/resources/application.yml
          echo "${{ secrets.APPLICATION }}" > ./src/main/resources/application.yml
          cat ./src/main/resources/application.yml

      # (4) Gradle 빌드
      - name: Grant execute permission for gradlew
        run: chmod +x ./gradlew

      - name: Build with Gradle
        run: ./gradlew build

      # (5) Docker Hub에 이미지 빌드 및 푸시
      - name: Docker Build and Push
        run: |
          docker login -u ${{ secrets.DOCKERHUB_USERNAME }} -p ${{ secrets.DOCKERHUB_PASSWORD }}
          docker build -t bambee-friend .
          docker tag bambee-friend bambee83/bambee-friend:${GITHUB_SHA::7}
          docker push bambee83/bambee-friend:${GITHUB_SHA::7}

      # (6) 원격 서버에 배포
      - name: Deploy to Remote Server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SERVER_KEY }}
          port: 22
          envs: GITHUB_SHA
          script: |
            podman login -u ${{ secrets.DOCKERHUB_USERNAME }} -p ${{ secrets.DOCKERHUB_PASSWORD }}
            podman pull bambee83/bambee-friend:${GITHUB_SHA::7}
            podman tag bambee83/bambee-friend:${GITHUB_SHA::7} bambee-friend
            echo "Tagging Image..."