# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.
# This workflow will build a Java project with Gradle and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-java-with-gradle

name: Gradle Build & Podman-Compose Deploy
# Main 브랜치에 push 될 때 해당 workflow 실행
on:
  push:
    branches: [ "main" ]

env:
  S3_BUCKET_NAME: nextdev-deploy

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      # (1) 기본 체크아웃
      - name: Checkout
        uses: actions/checkout@v3

      - uses: actions/checkout@v3
      - run: touch ./src/main/resources/application.properties
      - run: echo "${{ secrets.APPLICATION }}" > ./src/main/resources/application.yml
      - run: cat ./src/main/resources/application.yml

      # (2) JDK 11 세팅
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'

#       (3) Gradle build
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Build with Gradle
        run: ./gradlew clean build -x test


      # (4)
      - name: Make Directory & zip file
        run: |
          mkdir -p deploy
          cp ./build/libs/*.jar ./deploy
          cp .*.sh ./deploy
          zip -r ./nextDev.zip ./deploy
          

      # (5)
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-northeast-2

      - name: Upload to S3
        run: aws s3 cp --region ap-northeast-2 ./nextDev.zip s3://$S3_BUCKET_NAME/

      # (6)
      - name: Deploy
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        run: |
          aws deploy create-deployment \
          --application-name nextdev \
          --deployment-group-name nextdev-group \
          --file-exists-behavior OVERWRITE \
          --s3-location bucket=nextdev-deploy,bundleType=zip,key=nextDev.zip \ 
          --region ap-northeast-2